### ISSUE TITLE
Confusion on testing message padding sizes

### ISSUE THREAD

**Issue by VnUgE** [paulmillr/nip44#21]
So I'm building more extensive tests for noscrypt and realized when testing message padding sizes, we are assuming a message length of 65536 (line 405 in nip44.vectors.json) are valid, but 65536 is considered invalid as a message size on line 517 in the vectors file. 

What am I missing during my testing? I want to make sure I properly guard my functions.

**Comment by paulmillr** [comment]
calc_padded_len is just for testing padding function, which is usually separate. 65536 is invalid size of plaintext, but valid size of padded text.
